name: Run Snyk Security Scans

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk-scans:
    uses: ./.github/workflows/snyk-scan.yml@main
    with:
      project-directory: '.'
      snyk-token: secrets.SNYK_TOKEN